apiVersion: v1
kind: Service
metadata:
  labels:
    service-template-service.service: address-book-develop
  name: address-book-develop
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "5000"
spec:
  ports:
  - name: "address-book"
    port: 8080
    targetPort: 8080
  selector:
    address-book.service: address-book-develop
  #type: NodePort
